### ISSUE TITLE
Реализовать возможность прослушивания примера звучания инструмента. 

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#103]
1. Добавить возможность прослушивания примера звучания определенного инструмента, используя html5 audio.
2. **Внимание**: Firefox не поддерживает формат mp3. Оптимальный формат аудио, поддерживаемый всеми современными браузерами - `.ogg`

**Comment by eovolkov** [comment]
103_eovolkov

**Comment by yakovenkodenis** [comment]
@eovolkov Возможно, тебе будет интересно посмотреть это видео: [html5 audio](https://www.youtube.com/watch?v=mBSsef52kT8&index=16&list=PLLnpHn493BHGlqEn4EE7dRUnPn4o_tKM0)
