### ISSUE TITLE
Добавить отношения в таблицы (Piano, Order, OrderStatus)

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#20]
1. Сделать git pull development
2. Создать миграцию командой вида `rails g migration add_first_table_to_second_table first_table:references`, где first_table - это таблица, в модели которой должно быть `belongs_to`, а second_table - таблица, в модели которой должно быть `has_one` или `has_many`, в зависимости от отношения между таблицами. 
3. Сгенерируется файл миграции, в котором будет прописано что-то вроде `add_reference :second_table, :first_table, index: true, foreign_key: true`
4. Поскольку изменить нужно 3 своих таблицы, то `add_reference` должен быть прописан минимум трижды, по 1 для каждой внешней ссылки.
5. добавить туда же в метод `change` прямо **перед** `add_reference` строки вида `remove_column :table_name, :column_name`, для удаления тех колонок, которые должны были служить ссылками на другие таблицы. `remove_column` также должен быть прописан для каждой ненужной колонки.
6. Сделать pull request.

**Comment by yakovenkodenis** [comment]
done.

**Comment by eovolkov** [comment]
У тебя пропещена связь Product с Piano 
В Product надо добавить  
has_one :piano

**Comment by yakovenkodenis** [comment]
работаю в ветке `20_dyakovenko`

**Comment by yakovenkodenis** [comment]
Поменял ссылочные поля с множественного числа на единственное. 
`products_id` => `product_id`
`users_id` => `user_id`
Добавил в таблицу Products `has_one :piano`

finished.
