### ISSUE TITLE
05/08/2015 12:00 Добавить отношения в таблицы (Guitar, Product, ProductsCategory)

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#21]
1. Сделать git pull development
2. Создать миграцию командой вида `rails g migration add_first_table_to_second_table first_table:references`, где first_table - это таблица, в модели которой должно быть `belongs_to`, а second_table - таблица, в модели которой должно быть `has_one` или `has_many`, в зависимости от отношения между таблицами. 
3. Сгенерируется файл миграции, в котором будет прописано что-то вроде `add_reference :second_table, :first_table, index: true, foreign_key: true`
4. Поскольку изменить нужно 3 своих таблицы, то `add_reference` должен быть прописан минимум трижды, по 1 для каждой внешней ссылки.
5. добавить туда же в метод `change` прямо **перед** `add_reference` строки вида `remove_column :table_name, :column_name`, для удаления тех колонок, которые должны были служить ссылками на другие таблицы. `remove_column` также должен быть прописан для каждой ненужной колонки.
6. Сделать pull request.

**Comment by yakovenkodenis** [comment]
Небольшое уточнение:

Таск считается выполненным и готовым для pull request'а, если:
1. успешно выполняется команда `rake db:reset db:migrate`
2. после выполнения команды в пункте 1, в соответствующих таблицах есть нужные колонки и нет лишних (проверять через `psql -U postgres`).

**Comment by eovolkov** [comment]
21_evolkov

**Comment by eovolkov** [comment]
1. rails g migration RemovePartProductFromGuitars product_id
2. rails g migration AddProductsRefToGuitars product:references
3. rails g migration RemovePartProductCategoryFromProducts category_id
4. rails g migration AddProductsCategoriesRefToProducts products_category:references
5. Add references Product one-to-one Guitar, Product many-to-one Products_Category
6. rails g migration RemovePartProductFromOrdersProducts product_id
7. rails d migration AddProductsRefToOrdersProducts product:references
8. Add references Product many-to-one OrdersProducts
