### ISSUE TITLE
05/08/2015 12:00 Добавить отношения в таблицы (Violin, OrdersProducts)

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#22]
1. Сделать git pull development
2. Создать миграцию командой вида `rails g migration add_first_table_to_second_table first_table:references`, где first_table - это таблица, в модели которой должно быть `belongs_to`, а second_table - таблица, в модели которой должно быть `has_one` или `has_many`, в зависимости от отношения между таблицами. 
3. Сгенерируется файл миграции, в котором будет прописано что-то вроде `add_reference :second_table, :first_table, index: true, foreign_key: true`
4. Поскольку изменить нужно 2 своих таблицы, то `add_reference` должен быть прописан минимум дважды, по 1 для каждой внешней ссылки.
5. добавить туда же в метод `change` прямо **перед** `add_reference` строки вида `remove_column :table_name, :column_name`, для удаления тех колонок, которые должны были служить ссылками на другие таблицы. `remove_column` также должен быть прописан для каждой ненужной колонки.
6. Сделать pull request.

**Comment by yakovenkodenis** [comment]
Небольшое уточнение:

Таск считается выполненным и готовым для pull request'а, если:
1. успешно выполняется команда `rake db:reset db:migrate`
2. после выполнения команды в пункте 1, в соответствующих таблицах есть нужные колонки и нет лишних (проверять через `psql -U postgres`).

**Comment by Serg1i** [comment]
Work Started

**Comment by eovolkov** [comment]
22_evolkov

**Comment by eovolkov** [comment]
1. rails g migration AddProductToViolin product:references
2. rails g migration RemovePartProductFromViolin product_id
3. Add relation Product one-to-one Violin

**Comment by yakovenkodenis** [comment]
работаю в 22_dyakovenko

**Comment by yakovenkodenis** [comment]
удалил колонку order_id из orders_products, поскольку она не была внешним ключем.
выполнил следующую миграцию:

``` ruby
remove_column :orders_products, :order_id, :integer
add_reference :orders_products, :order, index: true, foreign_key: true
```

**Comment by yakovenkodenis** [comment]
improved.
