### ISSUE TITLE
11/08/2015 00:30. Написать тесты для User, Violin, OrderStatus

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#34]
1. Сделать git pull.
2. В папке `spec/models` написать тесты для `user_spec.rb`, `violin_spec.rb`,  `order_status_spec.rb`. 
   
   В каждом файле внутри блока `RSpec.describe ModelName, type: :model` должно быть еще два блока `describe 'validations' do ... end` и `describe 'associations' do ... end`.
   
   В блоке `validations` должны быть тесты для валидаций в соответствующей модели (сами валидации напишем позже, сначала тесты). 
   Пример теста на валидацию: 
   
   ``` ruby
   it { should validate_presence_of :name }
   it { should validate_uniqueness_of :project }
   it { should allow_value('Hello').for(:greeting) }
   it { should_not allow_value('@%&#').for(:name) }
   ```
   
   В блоке `associations` должны быть тесты для уже существующих ассоциаций моделей.  Пример: 
   
   ``` ruby
   it { should belong_to :owner }
   it { should have_one :nose }
   ```
   
   Все возможные метчеры можно посмотреть по этой ссылке: [shoulda_matchers](https://github.com/thoughtbot/shoulda-matchers).
3. **После** написания тестов, добавить соответствующие валидации в модели.
4. Добиться прохождения всех тестов. Для прогонки тестов удобнее использовать `guard`. Как его использовать - смотреть в wiki-страницах [`Использование Guard`](https://github.com/RubyBursaRelsohod/team_project/wiki/%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-Guard).
5. Сделать pull request и добиться одобрения HoundCI, а также успешного прохождения тестов на CircleCI.

**Comment by yakovenkodenis** [comment]
Если при попытке прогнать тесты появляется такая ошибка:

``` bash
Migrations are pending. To resolve this issue, run:

    bin/rake db:migrate RAILS_ENV=test
```

нужно запустить `rake db:test:prepare`

**Comment by Serg1i** [comment]
Started

**Comment by Serg1i** [comment]
May be closed with PR50 merge
