### ISSUE TITLE
Добавить регистрацию и аутентификацию с devise

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#41]
1. Сделать git pull
2.  Выполнить `rake db:migrate:reset`
3. **Выполнять `rails g devise:install` и `rails g simple_form:install` не нужно!**
4. Добавить функционал регистрации и аутентификации, используя `devise` и `simple_form` 
5. Внешний вид не важен, пусть пока будет то, что получиться автоматом. Единственное, что  нужно изменить - заменить `form_for` на `simple_form_for`, и все элементы `label` заменить на  плейсхолдеры. Пример генерации формы:
   
   ``` ruby
   <%= simple_form_for @user do |f| %>
     <%= f.input :email, placeholder: 'Email' %>
     <%= f.button :submit %>
   <% end %>
   ```
6. Вставить ссылки для логина и регистрации в `views/layouts/application.html.erb`
7. Сделать pull request.

**Comment by yakovenkodenis** [comment]
Полезные ссылки:
https://github.com/plataformatec/simple_form
https://github.com/plataformatec/devise
https://www.youtube.com/watch?v=ZEk0Jp2dThc  <--- на этом скринкасте показаны все функции,  которые нам нужны
https://www.youtube.com/watch?v=zJYuLebl-Js

**Comment by Dioscur** [comment]
41_dt

**Comment by Dioscur** [comment]
Done
