### ISSUE TITLE
Создать Violin, OrdersProducts

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#6]
1. Придумать 3-7 полей (характеристик) для таблицы Violin.
2. В соответствии с диаграммой по ссылке http://dbdesigner.net/designer/schema/7089 создать модели Violin, OrdersProducts и миграции для них (работать в новой ветке на основе ветки development).
3. Добиться безошибочного выполнения команды 'rake db:migrate' и корректной генерации pdf-диаграммы ('bundle exec erd') своей части бд.
4. Сделать pull request в ветку development . При наличии нарушений code conventions, к pull request'у напишет комментарий HoundCI, укажет где и что нужно исправить. Нужно добиться его одобрения.
5. Ждать принятия pull request'а

PS: при миграции бд rails ставит название таблицы во множественное число - ну и пусть.

**Comment by Serg1i** [comment]
Pull request created and merged. Issue closed
