### ISSUE TITLE
Add development gems

### ISSUE THREAD

**Issue by eovolkov** [RubyBursaRelsohod/team_project#65]
1. _https://github.com/evrone/quiet_assets_
   Quiet Assets turns off the Rails asset pipeline log. This means that it suppresses messages in your development log such as:

Started GET "/assets/application.js" for 127.0.0.1 at 2015-01-28 13:35:34 +0300
Served asset /application.js - 304 Not Modified (8ms)

Support Ruby on Rails >= 3.1
1. _https://github.com/ctran/annotate_models_
   Add a comment summarizing the current schema to the top or bottom of each of your…
   
   ActiveRecord models
   
   Fixture files
   
   Tests and Specs
   
   Object Daddy exemplars
   
   Machinist blueprints
   
   Fabrication fabricators
   
   Thoughtbot's factory_girl factories, i.e. the (spec|test)/factories/<model>_factory.rb files
   
   routes.rb file (for Rails projects)

The schema comment looks like this:
# == Schema Info
# 
# Table name: line_items
# 
# id                  :integer(11)    not null, primary key
# quantity            :integer(11)    not null
# product_id          :integer(11)    not null
# unit_price          :float
# order_id            :integer(11)
# 

 class LineItem < ActiveRecord::Base
   belongs_to :product
  . . .

It also annotates geometrical columns, geom type and srid, when using SpatialAdapter, PostgisAdapter or PostGISAdapter:
# == Schema Info
# 
# Table name: trips
# 
# local           :geometry        point, 4326
# path            :geometry        line_string, 4326

Also, if you pass the -r option, it'll annotate routes.rb with the output of +rake routes+.

**Comment by yakovenkodenis** [comment]
done.
