### ISSUE TITLE
19/08/2015 23:30. Добавить функционал paperclip.

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#69]
1. Находясь в ветке `development` выполнить `git pull origin development`.
2. Создать миграцию, создающую таблицу с картинками для товара и добавить ссылку на неё в Product (связь 1:M).
3. Создать миграцию, создающую таблицу с образцами звучания для товара и добавить ссылку на неё в Product (связь 1:M).
4. Используя гем `paperclip`, создать возможность добавления картинок и музыкальных образцов для товаров.
5. Сами файлы хранить на Amazon S3 (зарегистрировать там relsohod, используя командный email `relsohod@gmail.com`, пароль - в skype. Регистрация должна быть бесплатной).
6. Проверить работу функционала как в development режиме, так и в production (`RAILS_ENV=production rails s`).
7. Сделать pull request.

Полезные ссылки:
- [Paperclip Readme](https://github.com/thoughtbot/paperclip/blob/master/README.md)
- [Paperclip Tutorial](https://www.youtube.com/watch?v=PuyaLPFcn70)
- [Paperclip S3 Storage Docs](http://www.rubydoc.info/gems/paperclip/Paperclip/Storage/S3)

**Comment by eovolkov** [comment]
69_eovolkov
