### ISSUE TITLE
19/08/2015 23:30. Добавить разделение на роли с declarative_authorization

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#70]
1. Находясь в ветке `development` выполнить `git pull origin development`.
2. Используя гем `declarative_authorization`, добавить три роли: Guest, Client, Admin с соответствующими правами и уровнями доступа.
3. Guest - незарегистрированный пользователь. Не может выполнять покупки, не имеет доступка к профилю, только просмотр основных страниц.
4. Client - зарегистрированный пользователь. Имеет доступ к профилю, может его редактировать и делать покупки + имеет все права Guest.
5. Admin - администратор. Имеет абсолютные права, а также единственный, кто имеет доступ к url `localhost:3000/admin` (Остальных отправлять на главную страницу). 
6. Сделать pull request.

Полезные ссылки:
- [Declarative_authorization Readme](https://github.com/stffn/declarative_authorization/blob/master/README.rdoc)
- [Declarative_authorization Tutorial](https://www.youtube.com/watch?v=yfEthkWWMDo)

**Comment by Dioscur** [comment]
70_dt мой адресс
