### ISSUE TITLE
Баг при регистрации

### ISSUE THREAD

**Issue by eovolkov** [RubyBursaRelsohod/team_project#75]
После регстрации на почту приходит письмо с линком на подтверждение. В линке неправильный хост указан. Вот пример:
http://localhost:3000/users/confirmation?confirmation_token=YqR1kJ8NpHpEyURD8Vhw

**Comment by yakovenkodenis** [comment]
на локалхосте и в production работает правильно.

**Comment by eovolkov** [comment]
В продакшен тоже неправильный
http://relsohod.herokuapp.com/users/confirmation?confirmation_token=tgaaKws1sMebxy6xRt6C

Должен быть либо адресс компа с которого запущен сервер, либо забитый публичный домен.
Для девелопмента я думаю точно должен быть указан айпишник компа.

**Comment by Dioscur** [comment]
В продакшене как раз правильный, т.к. продакшен у нас на хероку
С девелопмент можно и поспорить, но все юзают localhost, так что не вижу смысла

**Comment by eovolkov** [comment]
Я не юзаю localhost. Ну да ладно. Пока не принцыпиально.
