### ISSUE TITLE
Создать Saxophone, User, Comment

### ISSUE THREAD

**Issue by yakovenkodenis** [RubyBursaRelsohod/team_project#8]
1. В соответствии с диаграммой по ссылке http://dbdesigner.net/designer/schema/7089 создать модели Saxophone, User, Comment и миграции для них (работать в новой ветке на основе ветки development).
2. Добиться безошибочного выполнения команды 'rake db:migrate' и корректной генерации pdf-диаграммы ('bundle exec erd') своей части бд. (пока что без связей)
3. Сделать pull request в ветку development . При наличии нарушений code conventions, к pull request'у напишет комментарий HoundCI, укажет где и что нужно исправить. Нужно добиться его одобрения.
4. Ждать принятия pull request'а

PS: при миграции бд rails ставит название таблицы во множественное число - ну и пусть.

**Comment by eovolkov** [comment]
Перепроверь все поля в таблицах в соответствии со схемой, пропущено поле product_id

**Comment by yakovenkodenis** [comment]
@eovolkov в связи с тем, что поля для ссылок оказались лишними, закрываю issue.
