### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by eovolkov** [RubyBursaRelsohod/team_project#85]
Сейчас у нас access_key_id и secret_access_key  для AWS S3 лежат в репозитории: environments/s3.yml

По нормальному это файлик должен подкладываться при деплое а в репозитории лежать пустым. 
Собственно вопрос: Мы можем это как-то реализовать для heroku иначе AWS нам заблокирует аккаунт к 26 августа?

**Comment by yakovenkodenis** [comment]
поменяли ключи.
